"use strict";
console.log("this is typescript file");
let data = "Hi";
let num = 100;
console.log("value of data is " + data);
console.log("value of num is " + num);
let data1 = "Hello";
let num1 = 200;
console.log("value of data1 is " + data1);
console.log("value of num1 is " + num1);
